name = "AntOptim"
uuid = "92e715ed-6b7e-4c66-9039-c12aac4e49fc"
authors = ["e193499a <lucas.baussay@etu.univ-nantes.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
